# Generated by Django 5.0.3 on 2024-03-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_verified_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
