# Generated by Django 5.0.3 on 2024-03-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_reset_password_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_language_code',
            new_name='language_code',
        ),
    ]
