# Generated by Django 5.0.3 on 2024-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename__language_code_user_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_code_is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
