# Generated by Django 5.0.3 on 2024-03-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_reset_password_code_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code_is_valid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
