# Generated by Django 5.0.3 on 2024-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_email_code_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_code_is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
