# Generated by Django 5.0.4 on 2024-04-22 11:43

import notification.models
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNotification',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('title_en', models.TextField(null=True)),
                ('title_ar', models.TextField(null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(null=True)),
                ('body_ar', models.TextField(null=True)),
                ('image', models.TextField(blank=True, max_length=500, null=True)),
                ('image_en', models.TextField(blank=True, max_length=500, null=True)),
                ('image_ar', models.TextField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical notification',
                'verbose_name_plural': 'historical notifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('title_en', models.TextField(null=True)),
                ('title_ar', models.TextField(null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(null=True)),
                ('body_ar', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True)),
                ('image_en', models.ImageField(blank=True, max_length=500, null=True)),
                ('image_ar', models.ImageField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
