# Generated by Django 5.0.3 on 2024-03-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
