# Generated by Django 5.0.3 on 2024-03-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='language_code',
        ),
    ]
