# Generated by Django 5.0.4 on 2024-04-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='notifications/images'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image_ar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='notifications/images'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image_en',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='notifications/images'),
        ),
    ]
