# Generated by Django 5.0.3 on 2024-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTranslationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='testtimemodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testtimemodel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='testtimemodel',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='testtimemodel',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testtimemodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='testtimemodel',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='testtimemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
