# Generated by Django 5.0.4 on 2024-04-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltest',
            name='bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltest',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
