# Generated by Django 5.0.4 on 2024-04-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='test',
            name='unique_active_un',
        ),
    ]
