# Generated by Django 5.0.3 on 2024-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_testtranslationmodel_remove_testtimemodel_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtranslationmodel',
            name='translated_text',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
