# Generated by Django 5.0.3 on 2024-03-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_testtranslationmodel_translated_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtranslationmodel',
            name='translated_text',
            field=models.JSONField(),
        ),
    ]
