# Generated by Django 5.0.3 on 2024-03-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
