# Generated by Django 5.0.6 on 2024-09-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('message', models.TextField()),
                ('html_message', models.TextField()),
                ('query_params', models.JSONField()),
                ('request_headers', models.JSONField()),
            ],
        ),
    ]
