# Generated by Django 5.0.3 on 2024-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='request_body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
