# Generated by Django 5.0.3 on 2024-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_log_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='request_body',
        ),
        migrations.RemoveField(
            model_name='log',
            name='response_body',
        ),
        migrations.RemoveField(
            model_name='log',
            name='status_code',
        ),
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(default='new', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(default='new'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
