# Generated by Django 5.0.3 on 2024-03-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_remove_log_request_body_remove_log_response_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='response_headers',
        ),
    ]
